[versions]
agp = "9.0.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
commonsLang3 = "3.12.0"
documentfile = "1.0.1"
httpclient5 = "5.0.3"
slf4jAndroid = "1.7.35"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
httpclient5 = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "httpclient5" }
slf4j-android = { module = "org.slf4j:slf4j-android", version.ref = "slf4jAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

