# Download translations form Crowdin & Recreate libretro_core_options_intl.h

name: Crowdin Translation Integration

on:
  schedule:
  # please choose a random time & weekday to avoid all repos synching at the same time
    - cron: '15 22 * * 5'  # Fridays at 10:15 PM, UTC

jobs:
  create_intl_file:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: 18
          distribution: zulu

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Create intl file
        shell: bash
        env:
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
        run: |
          python3 intl/download_workflow.py $CROWDIN_API_KEY "flyinghead-flycast" "shell/libretro/libretro_core_options_intl.h"

      - name: Commit files
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions[bot]"
          git add intl/*_workflow.py "shell/libretro/libretro_core_options_intl.h"
          git commit -m "Fetch translations & Recreate libretro_core_options_intl.h"

      - name: GitHub Push
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
