name: Nintendo Switch

on:
  push:
    branches-ignore:
      - 'l10n_**'
  pull_request:

jobs:
  build:
    name: Switch ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    strategy:
      matrix:
        config:
          - {name: standalone, destDir: switch}
          - {name: libretro, cmakeArgs: -DLIBRETRO=ON}

    steps:
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get -y install ccache cmake

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Mark git repository as safe
        run: git config --global --add safe.directory $PWD

      - uses: actions/cache@v5
        with:
          path: ~/.ccache
          key: ccache-switch-${{ matrix.config.name }}-${{ github.sha }}
          restore-keys: ccache-switch-${{ matrix.config.name }}-

      - name: CMake
        run: |
          $DEVKITPRO/portlibs/switch/bin/aarch64-none-elf-cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=artifact -G Ninja ${{ matrix.config.cmakeArgs }}
          cmake --build build --config Release --target install

      - uses: actions/upload-artifact@v6
        with:
          name: flycast-switch-${{ matrix.config.name }}
          path: |
            artifact/bin
            artifact/lib/libretro

      - name: Package app
        run: zip -m artifact/bin/flycast.nro.zip artifact/bin/flycast.nro
        if: hashFiles('artifact/bin/flycast.nro') != ''

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          version: v1.69.1

      - name: Upload to S3
        run: rclone copy artifact/bin scaleway:flycast-builds/${{ matrix.config.destDir }}/${GITHUB_REF#refs/}-$GITHUB_SHA
        if: github.repository == 'flyinghead/flycast' && github.event_name == 'push' && matrix.config.destDir != ''
